<x-guest-layout>
    @include('RealEstate.modules.single-header')
    <main>
        @include('RealEstate.modules.slider')
        @include('RealEstate.modules.furnishing')
        @include('RealEstate.modules.description')
        @include('RealEstate.modules.video')
    </main>
</x-guest-layout>
